# CC=g++
# CFLAGS=-c -std=c++17

# LIB=mi_index.a
# LIBOBJS=mi_index.o

all:
# all: $(LIB)

# $(LIB): $(LIBOBJS)
# 	ar rcs $@ $^
# 	rm -f *.o

# mi_index.o: mi_index.cpp
# 	c++ $(CFLAGS) $^ -o $@

# clean:
# 	rm -f $(LIB) $(LIBOBJS)

